
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: favorite_task_development


test:
  <<: *default
  database: favorite_task_test


production:
  <<: *default
  database: favorite_task_production
  username: favorite_task
  password: <%= ENV['FAVORITE_TASK_DATABASE_PASSWORD'] %>
